In [143]:
import sqlite3
import pandas as pd
# Create your connection.
conn = sqlite3.connect('database.sqlite')

match = pd.read_sql_query("SELECT * FROM match", conn)

In [144]:
pd.options.display.max_columns = None

In [145]:
match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB

In [146]:
match.shape

(25979, 115)

In [147]:
pd.options.display.max_columns = None

In [148]:
match.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [149]:
home = match[['match_api_id','home_player_Y1','home_player_Y2',
                        'home_player_Y3','home_player_Y4','home_player_Y5','home_player_Y6','home_player_Y7',
                        'home_player_Y8','home_player_Y9','home_player_Y10','home_player_Y11']].copy()

In [150]:
home.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Data columns (total 12 columns):
match_api_id       25979 non-null int64
home_player_Y1     24158 non-null float64
home_player_Y2     24158 non-null float64
home_player_Y3     24147 non-null float64
home_player_Y4     24147 non-null float64
home_player_Y5     24147 non-null float64
home_player_Y6     24147 non-null float64
home_player_Y7     24147 non-null float64
home_player_Y8     24147 non-null float64
home_player_Y9     24147 non-null float64
home_player_Y10    24147 non-null float64
home_player_Y11    24147 non-null float64
dtypes: float64(11), int64(1)
memory usage: 2.4 MB

In [151]:
home = home.dropna()

In [152]:
home.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24147 entries, 144 to 25978
Data columns (total 12 columns):
match_api_id       24147 non-null int64
home_player_Y1     24147 non-null float64
home_player_Y2     24147 non-null float64
home_player_Y3     24147 non-null float64
home_player_Y4     24147 non-null float64
home_player_Y5     24147 non-null float64
home_player_Y6     24147 non-null float64
home_player_Y7     24147 non-null float64
home_player_Y8     24147 non-null float64
home_player_Y9     24147 non-null float64
home_player_Y10    24147 non-null float64
home_player_Y11    24147 non-null float64
dtypes: float64(11), int64(1)
memory usage: 2.4 MB

In [153]:
from collections import Counter

In [154]:
def convert_num_string(s,oth=''):   
    """Transforms the format of a int or float to a string"""
    nums = '0123456789'   
    for c in s:   
        if (c in nums) == False:   
             s = s.replace(c,'');   
    return s

In [155]:
home_formation = {}

In [160]:
#every row is a match, take out formation according to Y coordinates
for index,row in home.iterrows():
    home_player_y = list()
    
    #create two list to store Y coordinate for each team,and they should be empty when we start parse a new match
    
    for i in range(2,12):
        home_player_y.append(row['home_player_Y%d' % i])
    #put teams's Y coordinates into list   
    

    c_home = Counter(home_player_y)
    #transform list to Counter objects
    formation_home = Counter(sorted(c_home.elements())).values()
    #sorted,for example: Y coordinate may be record wrong, like "5,5,3,3,3,3,5,7,7,10",
    #the correct formation should be 4321,
    #but if we don't sorted it, we will get 3421
    formation_home = convert_num_string(str(formation_home))
    #get only number, like '442', but it is still a string.
    
    home_formation.update({row['match_api_id'] : formation_home})
    #update match id and formation to dict

In [161]:
first_five_formations = list(home_formation.values())[:5]
first_five_matches= list(home_formation.keys())[:5]

In [162]:
for i in first_five_matches:
    print(f'The first five match IDs are {i}')
for j in first_five_formations:
    print(f'The first five formations are {j}')

The first five match IDs are 493016.0
The first five match IDs are 493017.0
The first five match IDs are 493018.0
The first five match IDs are 493019.0
The first five match IDs are 493020.0
The first five formations are 442
The first five formations are 442
The first five formations are 442
The first five formations are 442
The first five formations are 442

In [109]:
home['home_formation'] = home['match_api_id'].map(home_formation)

In [110]:
home.drop(columns=['home_player_Y1','home_player_Y2','home_player_Y3','home_player_Y4',
'home_player_Y5','home_player_Y6','home_player_Y7','home_player_Y8',
'home_player_Y9','home_player_Y10','home_player_Y11'],inplace = True)

KeyError: "['home_player_Y1' 'home_player_Y2' 'home_player_Y3' 'home_player_Y4'\n 'home_player_Y5' 'home_player_Y6' 'home_player_Y7' 'home_player_Y8'\n 'home_player_Y9' 'home_player_Y10' 'home_player_Y11'] not found in axis"

In [111]:
home.head()

     match_api_id home_formation
144        493016            442
145        493017            442
146        493018            442
147        493019            442
148        493020            442